import turtle as pen
pen.penup()
pen.goto(-15,-200)
pen.pendown()
pen.fillcolor("light blue")
pen.begin_fill()
pen.circle(230)
pen.end_fill()

pen.penup()
pen.goto(-100,-100)
pen.pendown()
pen.begin_fill()
pen.fillcolor("blue")
for i in range(2):
    pen.forward(50)
    pen.left(90)
    pen.forward(25)
    pen.left(90)

pen.penup()
pen.goto(0,-100)
pen.pendown()
for i in range(2):
    pen.forward(50)
    pen.left(90)
    pen.forward(25)
    pen.left(90)
pen.end_fill()

pen.pendown()
pen.goto(0,-75)
pen.begin_fill()
pen.fillcolor("gray")
for i in range(2):
    pen.forward(25)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
pen.forward(25)

pen.penup()
pen.goto(-75,-75)
pen.pendown()
for i in range(2):
    pen.forward(25)
    pen.left(90)
    pen.forward(100)
    pen.left(90)
pen.forward(25)
pen.end_fill()

pen.penup()
pen.goto(-75,25)
pen.pendown()
pen.begin_fill()
pen.fillcolor("red")
for i in range(2):
    pen.forward(100)
    pen.left(90)
    pen.forward(125)
    pen.left(90)
pen.end_fill()

pen.penup()
pen.goto(-75,150)
pen.pendown()
pen.begin_fill()
pen.fillcolor("gray")
pen.backward(50)
pen.left(90)
pen.forward(50)
pen.left(90)
pen.forward(25)
pen.left(90)
pen.forward(75)
pen.left(90)
pen.forward(75)
pen.left(90)
pen.forward(25)
pen.end_fill()

pen.penup()
pen.goto(25,150)
pen.pendown()
pen.begin_fill()
pen.fillcolor("gray")
pen.left(90)
pen.backward(50)
pen.right(90)
pen.forward(50)
pen.right(90)
pen.forward(25)
pen.right(90)
pen.forward(75)
pen.right(90)
pen.forward(75)
pen.right(90)
pen.forward(25)
pen.end_fill()

pen.penup()
pen.goto(-35,150)
pen.pendown()
pen.begin_fill()
pen.fillcolor("gray")
for i in range(4):
    pen.forward(25)
    pen.right(90)
pen.end_fill()

pen.penup()
pen.goto(-25,175)
pen.pendown()
pen.begin_fill()
pen.fillcolor("red")
pen.left(90)
pen.forward(40)
pen.right(90)
pen.forward(50)
pen.right(90)
pen.forward(85)
pen.right(90)
pen.forward(50)
pen.right(90)
pen.forward(40)
pen.end_fill()

pen.penup()
pen.goto(-25,185)
pen.pendown()
pen.begin_fill()
pen.fillcolor("black")
pen.forward(20)
pen.right(90)
pen.forward(7)
pen.right(90)
pen.forward(40)
pen.right(90)
pen.forward(7)
pen.right(90)
pen.forward(20)
pen.end_fill()

pen.penup()
pen.goto(-25,200)
pen.pendown()
pen.begin_fill()
pen.fillcolor("white")
pen.forward(17)
pen.right(90)
pen.forward(15)
pen.right(90)
pen.forward(34)
pen.right(90)
pen.forward(15)
pen.right(90)
pen.forward(17)
pen.end_fill()

pen.penup()
pen.goto(-30,200)
pen.pendown()
pen.begin_fill()
pen.fillcolor("black")
for i in range(4):
    pen.forward(8)
    pen.right(90)
pen.end_fill()

pen.penup()
pen.goto(-10,200)
pen.pendown()
pen.begin_fill()
pen.fillcolor("black")
for i in range(4):
    pen.forward(8)
    pen.right(90)
pen.end_fill()

